#!/usr/bin/env node
// Assemble the standalone single-file SillyGoose web app from src/ and src/lib/.
//
// Outputs everything the browser/PWA build needs into dist/:
//   dist/index.html            self-contained app (Plotly + JSZip + CSS + logo inlined)
//   dist/manifest.webmanifest  PWA manifest (installable / offline)
//   dist/service-worker.js     cache-first service worker
//
// Both consumers use dist/index.html: Electron loads it directly, and the
// deploy-web GitHub Action copies dist/ into the github.io repo.
//
// Node port of the original build.py. No third-party dependencies.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const ROOT = dirname(fileURLToPath(import.meta.url));
const SRC = resolve(ROOT, 'src');
const LIB = resolve(SRC, 'lib');
const ASSETS = resolve(SRC, 'assets');
const OUT_DIR = resolve(ROOT, 'dist');
const OUT = resolve(OUT_DIR, 'index.html');

function needText(path) {
  return readFileSync(path, 'utf-8');
}

function needBytes(path) {
  return readFileSync(path);
}

const plotlyJs = needText(resolve(LIB, 'plotly-2.27.0.min.js'));
const jszipJs = needText(resolve(LIB, 'jszip-3.10.1.min.js'));
const appCss = needText(resolve(SRC, 'app.css'));
let bodyHtml = needText(resolve(SRC, 'body.html'));
const appJs = needText(resolve(SRC, 'app.js'));

const logoBase64 = needBytes(resolve(ASSETS, 'logo.png')).toString('base64');
const logoDataUri = `data:image/png;base64,${logoBase64}`;
if (!bodyHtml.includes('{{LOGO_DATA_URI}}')) {
  throw new Error('Missing logo placeholder in src/body.html');
}
bodyHtml = bodyHtml.replaceAll('{{LOGO_DATA_URI}}', logoDataUri);

const thirdPartyNotice = `Plotly.js v2.27.0 - https://github.com/plotly/plotly.js
Copyright (c) 2012-2023 Plotly, Inc. Licensed MIT.

JSZip v3.10.1 - https://github.com/Stuk/jszip
Copyright (c) 2009-2016 Stuart Knightley. Licensed MIT or GPLv3.

Full license notes: see LICENSES.md alongside this file.`;

// Registers the service worker so the browser build works offline. Guarded so
// the same index.html runs unchanged under Electron (file://, no SW needed).
const pwaHead = `<link rel="manifest" href="manifest.webmanifest">
<meta name="theme-color" content="#0f172a">`;
const pwaScript = `
if ('serviceWorker' in navigator && location.protocol.startsWith('http')) {
  window.addEventListener('load', () => {
    navigator.serviceWorker.register('service-worker.js').catch(() => {});
  });
}`;

const html = `<!DOCTYPE html>
<!--
  SillyGoose Configuration Tool - standalone single-file build.
  Generated by build.mjs from src/. Do not edit this file directly;
  edit src/app.js, src/app.css, src/body.html, then re-run build.mjs.

  Bundled libraries:
  ${thirdPartyNotice}
-->
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SillyGoose Configuration Tool</title>
${pwaHead}
<style>
${appCss}
</style>
</head>
<body>
${bodyHtml}
<script>
/*! plotly.js v2.27.0 - MIT - https://github.com/plotly/plotly.js */
${plotlyJs}
</script>
<script>
/*! JSZip v3.10.1 - MIT or GPLv3 - https://github.com/Stuk/jszip */
${jszipJs}
</script>
<script>
${appJs}
</script>
<script>${pwaScript}
</script>
</body>
</html>
`;

const manifest = JSON.stringify(
  {
    name: 'SillyGoose Configuration Tool',
    short_name: 'SillyGoose',
    start_url: '.',
    scope: '.',
    display: 'standalone',
    background_color: '#0f172a',
    theme_color: '#0f172a',
    icons: [
      {
        src: 'data:image/png;base64,' + logoBase64,
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any'
      }
    ]
  },
  null,
  2
);

// Cache-first worker. Bump CACHE on every build so a new index.html replaces the
// cached copy instead of serving a stale single-file app forever.
const cacheName = `sillygoose-${Buffer.from(html).length}`;
const serviceWorker = `const CACHE = '${cacheName}';
const ASSETS = ['./', './index.html', './manifest.webmanifest'];
self.addEventListener('install', (e) => {
  self.skipWaiting();
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k)))
    )
  );
  self.clients.claim();
});
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return;
  e.respondWith(
    caches.match(e.request).then((hit) => hit || fetch(e.request))
  );
});
`;

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(OUT, html, 'utf-8');
writeFileSync(resolve(OUT_DIR, 'manifest.webmanifest'), manifest, 'utf-8');
writeFileSync(resolve(OUT_DIR, 'service-worker.js'), serviceWorker, 'utf-8');

const size = Buffer.from(html).length;
console.log(`Built ${OUT} (${size.toLocaleString()} bytes / ${(size / 1024).toFixed(1)} KB)`);
console.log('Built dist/manifest.webmanifest, dist/service-worker.js');
